## Cross-package parity: R outputs must match the webtool fixture.
##
## The webtool (TypeScript) is the reference implementation for the
## v2.2.2 statistics additions (item share distribution + cluster set
## order). The fixtures under python/tests/fixtures/expected/ are
## generated by scripts/dump_expected_fixtures.ts from the live TS code
## on the 4-set cancer-drivers dataset; this file asserts the R package
## reproduces them exactly.
##
## Note on coordinates: the webtool / Python emit a 0-based leaf order,
## R returns a 1-based leaf order. We translate before comparing.
## Similarly, merges expose 0-based cluster ids in all three packages.

.fixtures_dir <- function() {
    here <- testthat::test_path()
    candidates <- c(
        file.path(here, "..", "..", "..", "python", "tests", "fixtures", "expected"),
        file.path(here, "..", "..", "fixtures", "expected")
    )
    for (cand in candidates) {
        if (dir.exists(cand)) return(normalizePath(cand))
    }
    NULL
}

.dataset_path <- function() {
    p <- system.file("extdata", "samples",
                     "dataset_real_cancer_drivers_4.tsv",
                     package = "vennDiagramLab")
    if (!nzchar(p) || !file.exists(p)) {
        p <- file.path(testthat::test_path(), "..", "..", "..",
                       "data", "dataset_real_cancer_drivers_4.tsv")
    }
    p
}

## Re-derive the binary item-by-set matrix from a VennDataset. Mirrors
## the private helper in render-share-distribution.R so we don't depend
## on internal symbols here.
.binary_matrix <- function(ds) {
    set_names <- ds@set_names
    rows <- ds@item_order
    if (length(rows) == 0L) {
        seen <- character()
        for (name in set_names) {
            for (item in ds@items[[name]]) {
                if (!item %in% seen) seen <- c(seen, item)
            }
        }
        rows <- seen
    }
    n_rows <- length(rows)
    n_cols <- length(set_names)
    m <- matrix(0L, nrow = n_rows, ncol = n_cols,
                dimnames = list(NULL, set_names))
    if (n_rows == 0L) return(m)
    row_idx <- setNames(seq_along(rows), rows)
    for (j in seq_len(n_cols)) {
        for (item in ds@items[[set_names[j]]]) {
            i <- row_idx[[item]]
            if (!is.null(i)) m[i, j] <- 1L
        }
    }
    m
}

## D = 1 - Jaccard, diagonal zeroed and symmetrized. Mirrors the
## private helper in render-share-distribution.R.
.jaccard_distance <- function(result) {
    stats_res <- vennDiagramLab::statistics(result)
    jacc <- stats_res@jaccard
    n <- length(result@dataset@set_names)
    if (length(jacc) == 0L || n < 2L) return(matrix(0, nrow = n, ncol = n))
    D <- 1 - jacc
    diag(D) <- 0
    (D + t(D)) / 2
}

test_that("share distribution matches webtool fixture", {
    fd <- .fixtures_dir()
    skip_if(is.null(fd), "webtool fixtures not available")
    fp <- file.path(fd, "share_distribution_4set.json")
    skip_if(!file.exists(fp), "share_distribution_4set.json missing")
    skip_if_not_installed("jsonlite")

    expected <- jsonlite::fromJSON(fp)
    ds <- vennDiagramLab::load_tsv(.dataset_path(), binary = TRUE,
                                   prefix_cols = 1L)
    m <- .binary_matrix(ds)
    got <- vennDiagramLab::item_share_distribution(m)

    expect_equal(sum(as.integer(got)), 1394L)
    for (k in names(expected)) {
        expect_equal(as.integer(got[k]), as.integer(expected[[k]]),
                     info = paste("k =", k))
    }
})

test_that("cluster leaf order + merges match webtool fixture", {
    fd <- .fixtures_dir()
    skip_if(is.null(fd), "webtool fixtures not available")
    fp <- file.path(fd, "cluster_order_4set.json")
    skip_if(!file.exists(fp), "cluster_order_4set.json missing")
    skip_if_not_installed("jsonlite")

    expected <- jsonlite::fromJSON(fp)
    ds <- vennDiagramLab::load_tsv(.dataset_path(), binary = TRUE,
                                   prefix_cols = 1L)
    res <- vennDiagramLab::analyze(ds)
    D <- .jaccard_distance(res)
    co <- vennDiagramLab::cluster_set_order(D, linkage = "average")

    ## R leaf_order is 1-based; webtool is 0-based. Translate.
    got_leaf_zero <- as.integer(co$leaf_order) - 1L
    expect_equal(got_leaf_zero, as.integer(expected$leafOrder))

    ## Merges: R returns a data.frame with columns left, right (0-based),
    ## height, size. Compare row-by-row against the webtool's array.
    exp_merges <- expected$merges
    expect_equal(nrow(co$merges), nrow(exp_merges))
    for (i in seq_len(nrow(co$merges))) {
        expect_equal(as.integer(co$merges$left[i]),
                     as.integer(exp_merges$left[i]),
                     info = paste("merge", i, "left"))
        expect_equal(as.integer(co$merges$right[i]),
                     as.integer(exp_merges$right[i]),
                     info = paste("merge", i, "right"))
        expect_equal(as.integer(co$merges$size[i]),
                     as.integer(exp_merges$size[i]),
                     info = paste("merge", i, "size"))
        expect_lt(abs(co$merges$height[i] - exp_merges$height[i]), 1e-9)
    }
})
