/**
 * Generate RegionData for 2-set area-proportional diagrams.
 * Uses line segments (M/L) like the JSON files generated by generate_region_json.py,
 * in normalized coordinates ([-50, 50] range, Y-flipped).
 */
import type { RegionData } from '../models.ts';
import type { ProportionalCircle } from './proportionalLayout.ts';

const COLORS: Record<string, string> = {
  A: '#FFF200', B: '#2E3192', C: '#ED1C24',
};

/** Convert pixel coords to normalized [-50, 50], Y-flipped. */
function toNorm(px: number, py: number, cs: number): [number, number] {
  return [
    Math.round(((px / cs) * 100 - 50) * 100) / 100,
    Math.round((-((py / cs) * 100 - 50)) * 100) / 100,
  ];
}

/** Generate polyline circle path as M/L segments in normalized coords. */
function circlePolyPath(cx: number, cy: number, r: number, cs: number, steps = 72): string {
  const pts: string[] = [];
  for (let i = 0; i <= steps; i++) {
    const angle = (2 * Math.PI * i) / steps;
    const px = cx + Math.cos(angle) * r;
    const py = cy + Math.sin(angle) * r;
    const [nx, ny] = toNorm(px, py, cs);
    pts.push(i === 0 ? `M ${nx} ${ny}` : `L ${nx} ${ny}`);
  }
  pts.push('Z');
  return pts.join(' ');
}

/**
 * Generate an arc polyline from angle1 to angle2 on circle (cx, cy, r).
 * Returns array of [nx, ny] normalized points.
 */
function arcPoints(cx: number, cy: number, r: number, a1: number, a2: number, cs: number, steps = 36): [number, number][] {
  const pts: [number, number][] = [];
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    const angle = a1 + (a2 - a1) * t;
    const px = cx + Math.cos(angle) * r;
    const py = cy + Math.sin(angle) * r;
    pts.push(toNorm(px, py, cs));
  }
  return pts;
}

/** Angle from circle center to a point. */
function angleTo(cx: number, cy: number, px: number, py: number): number {
  return Math.atan2(py - cy, px - cx);
}

/** Normalize angle to [0, 2π). */
function normAngle(a: number): number {
  while (a < 0) a += 2 * Math.PI;
  while (a >= 2 * Math.PI) a -= 2 * Math.PI;
  return a;
}

export function generate2SetRegions(
  circles: [ProportionalCircle, ProportionalCircle],
  canvasSize: number,
): RegionData {
  const [cA, cB] = circles;
  const dx = cB.cx - cA.cx;
  const dy = cB.cy - cA.cy;
  const d = Math.sqrt(dx * dx + dy * dy);
  const cs = canvasSize;

  const sets = ['A', 'B'];
  const regions: string[] = ['', '', '', ''];
  const region_labels: Record<string, [number, number]> = {};

  const curves = [
    circlePolyPath(cA.cx, cA.cy, cA.r, cs),
    circlePolyPath(cB.cx, cB.cy, cB.r, cs),
  ];

  // Disjoint
  if (d >= cA.r + cB.r) {
    regions[1] = circlePolyPath(cA.cx, cA.cy, cA.r, cs);
    regions[2] = circlePolyPath(cB.cx, cB.cy, cB.r, cs);
    region_labels['A'] = toNorm(cA.cx, cA.cy, cs);
    region_labels['B'] = toNorm(cB.cx, cB.cy, cs);
    return { name: 'Area-Proportional 2-set', n: 2, sets, curves, regions, colors: { A: COLORS.A, B: COLORS.B }, region_labels, set_names: { A: 'NameA', B: 'NameB' } };
  }

  // Containment: smaller inside larger
  if (d + Math.min(cA.r, cB.r) <= Math.max(cA.r, cB.r)) {
    const [outer, inner] = cA.r >= cB.r ? [cA, cB] : [cB, cA];
    const outerIdx = cA.r >= cB.r ? 1 : 2;
    regions[outerIdx] = circlePolyPath(outer.cx, outer.cy, outer.r, cs);
    regions[3] = circlePolyPath(inner.cx, inner.cy, inner.r, cs);
    region_labels[outer.letter] = toNorm(outer.cx + outer.r * 0.6, outer.cy, cs);
    region_labels['AB'] = toNorm(inner.cx, inner.cy, cs);
    return { name: 'Area-Proportional 2-set', n: 2, sets, curves, regions, colors: { A: COLORS.A, B: COLORS.B }, region_labels, set_names: { A: 'NameA', B: 'NameB' } };
  }

  // Normal intersection — compute intersection points
  const a = (cA.r * cA.r - cB.r * cB.r + d * d) / (2 * d);
  const h = Math.sqrt(Math.max(0, cA.r * cA.r - a * a));
  const px = cA.cx + a * dx / d;
  const py = cA.cy + a * dy / d;
  const p1 = [px + h * dy / d, py - h * dx / d] as [number, number];
  const p2 = [px - h * dy / d, py + h * dx / d] as [number, number];

  // Angles from each center to intersection points
  const aA1 = angleTo(cA.cx, cA.cy, p1[0], p1[1]);
  const aA2 = angleTo(cA.cx, cA.cy, p2[0], p2[1]);
  const aB1 = angleTo(cB.cx, cB.cy, p1[0], p1[1]);
  const aB2 = angleTo(cB.cx, cB.cy, p2[0], p2[1]);

  // Arc from p1 to p2 going through the intersection side (short arc toward other center)
  // For circle A: the "intersection arc" goes from p1 to p2 on the side facing B
  // For circle B: the "intersection arc" goes from p2 to p1 on the side facing A
  const midAngleAB = Math.atan2(cB.cy - cA.cy, cB.cx - cA.cx);
  const midAngleBA = Math.atan2(cA.cy - cB.cy, cA.cx - cB.cx);

  // Determine which arc of A faces B (intersection arc) vs away from B (exclusive arc)
  function sweepThrough(from: number, to: number, through: number): [number, number] {
    const f = normAngle(from);
    const t = normAngle(to);
    const th = normAngle(through);
    // CW from f to t
    const cw = normAngle(t - f);
    // Check if 'through' is within the CW arc
    const toTh = normAngle(th - f);
    if (toTh <= cw) return [f, f + cw]; // CW contains through
    return [f, f - (2 * Math.PI - cw)]; // CCW contains through
  }

  // A's intersection arc (from p1 to p2, passing near B)
  const [aIntStart, aIntEnd] = sweepThrough(aA1, aA2, midAngleAB);
  // A's exclusive arc (from p2 to p1, away from B)
  const [aExStart, aExEnd] = sweepThrough(aA2, aA1, midAngleAB + Math.PI);
  // B's intersection arc (from p2 to p1, passing near A)
  const [bIntStart, bIntEnd] = sweepThrough(aB2, aB1, midAngleBA);
  // B's exclusive arc (from p1 to p2, away from A)
  const [bExStart, bExEnd] = sweepThrough(aB1, aB2, midAngleBA + Math.PI);

  function buildPath(segments: [number, number][][]): string {
    const parts: string[] = [];
    for (let s = 0; s < segments.length; s++) {
      const seg = segments[s];
      for (let i = 0; i < seg.length; i++) {
        parts.push(i === 0 && s === 0 ? `M ${seg[i][0]} ${seg[i][1]}` : `L ${seg[i][0]} ${seg[i][1]}`);
      }
    }
    parts.push('Z');
    return parts.join(' ');
  }

  // Generate all four arcs
  const aIntPts = arcPoints(cA.cx, cA.cy, cA.r, aIntStart, aIntEnd, cs);
  const aExPts = arcPoints(cA.cx, cA.cy, cA.r, aExStart, aExEnd, cs);
  const bIntPts = arcPoints(cB.cx, cB.cy, cB.r, bIntStart, bIntEnd, cs);
  const bExPts = arcPoints(cB.cx, cB.cy, cB.r, bExStart, bExEnd, cs);

  // Region AB (lens): A's intersection arc + B's intersection arc
  regions[3] = buildPath([aIntPts, bIntPts]);

  // Region A exclusive: A's exclusive arc + B's intersection arc (reversed, closing the lens boundary)
  regions[1] = buildPath([aExPts, [...bIntPts].reverse()]);

  // Region B exclusive: B's exclusive arc + A's intersection arc (reversed)
  regions[2] = buildPath([bExPts, [...aIntPts].reverse()]);

  // Region labels
  const midAB = [(p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2];
  region_labels['AB'] = toNorm(midAB[0], midAB[1], cs);
  region_labels['A'] = toNorm(cA.cx * 1.4 - midAB[0] * 0.4, cA.cy * 1.4 - midAB[1] * 0.4, cs);
  region_labels['B'] = toNorm(cB.cx * 1.4 - midAB[0] * 0.4, cB.cy * 1.4 - midAB[1] * 0.4, cs);

  return {
    name: 'Area-Proportional 2-set diagram',
    n: 2,
    sets,
    curves,
    regions,
    colors: { A: COLORS.A, B: COLORS.B },
    region_labels,
    set_names: { A: 'NameA', B: 'NameB' },
  };
}

/**
 * Generate 3-set RegionData using grid sampling + contour tracing.
 * Produces 7 region paths in normalized coordinates.
 */
export function generate3SetRegions(
  circles: ProportionalCircle[],
  canvasSize: number,
): RegionData {
  const cs = canvasSize;
  const RES = 400; // grid resolution
  const step = cs / RES;

  // Build bitmask grid: for each cell, which circles contain the center?
  const grid: number[][] = [];
  for (let gy = 0; gy <= RES; gy++) {
    const row: number[] = [];
    for (let gx = 0; gx <= RES; gx++) {
      const px = gx * step;
      const py = gy * step;
      let mask = 0;
      for (let i = 0; i < circles.length; i++) {
        const c = circles[i];
        const dx = px - c.cx, dy = py - c.cy;
        if (dx * dx + dy * dy <= c.r * c.r) mask |= (1 << i);
      }
      row.push(mask);
    }
    grid.push(row);
  }

  // For each region (bitmask 1..7): extract boundary contour using simple edge tracing
  const sets = circles.map(c => c.letter);
  const n = circles.length;
  const totalRegions = (1 << n); // 8
  const regions: string[] = Array(totalRegions).fill('');
  const region_labels: Record<string, [number, number]> = {};

  for (let mask = 1; mask < totalRegions; mask++) {
    const label = sets.filter((_, i) => mask & (1 << i)).join('');
    const boundary = extractContour(grid, mask, RES, step, cs);
    if (boundary.length > 2) {
      const pathParts = boundary.map((p, i) =>
        (i === 0 ? `M ${p[0]} ${p[1]}` : `L ${p[0]} ${p[1]}`)
      );
      pathParts.push('Z');
      regions[mask] = pathParts.join(' ');
    }

    // Centroid for label
    let sumX = 0, sumY = 0, count = 0;
    for (let gy = 0; gy < RES; gy++) {
      for (let gx = 0; gx < RES; gx++) {
        if (grid[gy][gx] === mask) {
          sumX += gx * step + step / 2;
          sumY += gy * step + step / 2;
          count++;
        }
      }
    }
    if (count > 0) {
      region_labels[label] = toNorm(sumX / count, sumY / count, cs);
    }
  }

  // Curves (circle outlines)
  const curves = circles.map(c => circlePolyPath(c.cx, c.cy, c.r, cs));

  const colors: Record<string, string> = {};
  for (const c of circles) colors[c.letter] = COLORS[c.letter] ?? '#888';

  const set_names: Record<string, string> = {};
  for (const c of circles) set_names[c.letter] = `Name${c.letter}`;

  return {
    name: `Area-Proportional ${n}-set diagram`,
    n,
    sets,
    curves,
    regions,
    colors,
    region_labels,
    set_names,
  };
}

/**
 * Extract boundary contour of a region (cells matching targetMask) from the grid.
 * Returns normalized coordinate points forming a closed polygon.
 */
function extractContour(
  grid: number[][],
  targetMask: number,
  res: number,
  step: number,
  cs: number,
): [number, number][] {
  // Create binary image: 1 if cell matches targetMask, 0 otherwise
  const binary: boolean[][] = [];
  for (let gy = 0; gy <= res; gy++) {
    const row: boolean[] = [];
    for (let gx = 0; gx <= res; gx++) {
      row.push(grid[gy][gx] === targetMask);
    }
    binary.push(row);
  }

  // Find boundary pixels: cells that are 'inside' but have at least one 'outside' neighbor
  const boundaryPts: [number, number][] = [];
  for (let gy = 1; gy < res; gy++) {
    for (let gx = 1; gx < res; gx++) {
      if (!binary[gy][gx]) continue;
      const hasOutsideNeighbor =
        !binary[gy - 1][gx] || !binary[gy + 1][gx] ||
        !binary[gy][gx - 1] || !binary[gy][gx + 1];
      if (hasOutsideNeighbor) {
        boundaryPts.push(toNorm(gx * step, gy * step, cs));
      }
    }
  }

  if (boundaryPts.length === 0) return [];

  // Sort boundary points by angle from centroid for a closed contour
  let cx = 0, cy = 0;
  for (const [x, y] of boundaryPts) { cx += x; cy += y; }
  cx /= boundaryPts.length;
  cy /= boundaryPts.length;

  boundaryPts.sort((a, b) => {
    const angA = Math.atan2(a[1] - cy, a[0] - cx);
    const angB = Math.atan2(b[1] - cy, b[0] - cx);
    return angA - angB;
  });

  // Simplify: take every Nth point to reduce path size
  const skip = Math.max(1, Math.floor(boundaryPts.length / 200));
  const simplified: [number, number][] = [];
  for (let i = 0; i < boundaryPts.length; i += skip) {
    simplified.push(boundaryPts[i]);
  }

  return simplified;
}
