"""Cross-package parity: Python outputs must match the webtool fixture.

The webtool (TypeScript) is the reference implementation for the v2.2.2
statistics additions (item share distribution + cluster set order). The
fixtures under ``python/tests/fixtures/expected/`` are generated by
``scripts/dump_expected_fixtures.ts`` from the live TS code on the
4-set cancer-drivers dataset; this module asserts the Python package
reproduces them exactly.

If a test in this module fails, that is a real cross-package
disagreement and must be fixed in the Python implementation (or in the
fixture, if the TS source-of-truth changed intentionally) — never
``xfail``-ed away.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from venn_diagram_lab.analysis import analyze
from venn_diagram_lab.cluster import cluster_set_order
from venn_diagram_lab.io import Dataset, load_tsv
from venn_diagram_lab.share_distribution import item_share_distribution

FIXTURES = Path(__file__).parent / "fixtures" / "expected"
DATASET = Path(__file__).resolve().parents[2] / "data" / "dataset_real_cancer_drivers_4.tsv"


def _dataset_to_binary_matrix(ds: Dataset) -> np.ndarray:
    """Re-derive the binary item-by-set matrix from a Dataset.

    Mirrors the private helper in ``render/svg.py`` so we don't rely on
    internal symbols here. Rows = items (in ``item_order``), columns =
    sets (in ``set_names``).
    """
    set_names = ds.set_names
    rows = list(ds.item_order) if ds.item_order else sorted(
        {item for name in set_names for item in ds.items.get(name, set())}
    )
    matrix = np.zeros((len(rows), len(set_names)), dtype=int)
    row_idx = {item: i for i, item in enumerate(rows)}
    for j, name in enumerate(set_names):
        for item in ds.items.get(name, set()):
            i = row_idx.get(item)
            if i is not None:
                matrix[i, j] = 1
    return matrix


def _jaccard_distance_matrix(result) -> np.ndarray:
    """D = 1 - Jaccard, diagonal zeroed and symmetrized.

    Mirrors ``render/svg.py::_jaccard_distance_matrix``.
    """
    jacc = result.statistics.jaccard
    n = len(result.dataset.set_names)
    if jacc.empty or n < 2:
        return np.zeros((n, n), dtype=float)
    arr = jacc.to_numpy(dtype=float, copy=True)
    distance = 1.0 - arr
    np.fill_diagonal(distance, 0.0)
    return np.asarray((distance + distance.T) / 2.0, dtype=float)


def test_share_distribution_matches_webtool() -> None:
    ds = load_tsv(DATASET, binary=True, prefix_cols=1)
    matrix = _dataset_to_binary_matrix(ds)
    got = item_share_distribution(matrix)

    raw = json.loads((FIXTURES / "share_distribution_4set.json").read_text())
    expected = {int(k): int(v) for k, v in raw.items()}
    assert got == expected, (
        f"Item share distribution differs from webtool fixture.\n"
        f"  Python got: {got}\n"
        f"  Webtool:    {expected}"
    )
    # Sanity: total items in the cancer-drivers 4-set fixture is 1394.
    assert sum(got.values()) == 1394


def test_cluster_order_matches_webtool() -> None:
    ds = load_tsv(DATASET, binary=True, prefix_cols=1)
    res = analyze(ds)
    distance = _jaccard_distance_matrix(res)
    co = cluster_set_order(distance, method="average")

    expected = json.loads((FIXTURES / "cluster_order_4set.json").read_text())
    assert co.leaf_order == expected["leafOrder"], (
        f"Leaf order differs.\n"
        f"  Python got: {co.leaf_order}\n"
        f"  Webtool:    {expected['leafOrder']}"
    )
    assert len(co.merges) == len(expected["merges"])
    for got, want in zip(co.merges, expected["merges"], strict=True):
        assert got.left == want["left"], (got, want)
        assert got.right == want["right"], (got, want)
        assert got.size == want["size"], (got, want)
        assert abs(got.height - want["height"]) < 1e-9, (got, want)
